### ISSUE TITLE
The app references non-public selectors in Xcode 14

### ISSUE THREAD

**Issue by VestaCute** [yandexmobile/metrica-sdk-ios#105]
<img width="1432" alt="Снимок экрана 2022-09-14 в 12 13 50" src="https://user-images.githubusercontent.com/46375820/190127687-9f58fd37-2659-4c9e-b43a-11da5c6a8b46.png">

В Xcode 14 появилась новая проблема при выгрузке приложения в AppStore (приложение загружается, но с ошибками). В предыдущей версии Xcode этой ошибки не было

**Comment by AppMetricaOvermindGenius180iq** [comment]
Добрый день!Ваше письмо получено и зарегистрировано под уникальным номером № 19194647. Ответ обязательно будет предоставлен, пожалуйста, ожидайте.Просим Вас не отправлять повторное письмо по данному вопросу - оно будет считаться новой заявкой и может быть обработано позднее.Помощь сервиса: https://yandex.ru/support/direct/?from=email--С уважением,Отдел клиентского сервисател.: 8 800 234-24-80 (звонок из регионов России бесплатный)тел.: +7 495 739-37-77&nbsp14.09.2022, 13:15, "Vesta Cute" ***@***.***>:

В Xcode 14 появилась новая проблема при выгрузке приложения в AppStore (приложение загружается, но с ошибками). В предыдущей версии Xcode этой ошибки не было

**Comment by GLinnik21** [comment]
Здравствуйте. 
Спасибо за репорт. Подскажите, а есть ли проблемы с выкладкой уже в сам AppStore с этим ворнингом?

**Comment by GLinnik21** [comment]
Duplicate of #104

**Comment by AppMetricaOvermindGenius180iq** [comment]
Здравствуйте! Уточните, пожалуйста, по какому сервису у вас возник вопрос. Так же, чтобы мы смогли получить доступ на просмотр данных вашего рекламного кабинета в Яндекс.Директе и ответить на вопросы, пожалуйста, войдите в личный кабинет в Директе и напишите нам повторно через форму обратной связи:Зайдите на страницу с формой обратной связи.В правом верхнем углу страницы выберите логин, на котором вы размещаете рекламную кампанию в Директе.Отправьте вопрос. При необходимости прикрепите скриншот, иллюстрирующий ситуацию.При обращении через форму обратной связи проверяйте, под каким логином вы авторизованы - его можно увидеть в правом верхнем углу экрана. Авторизоваться на странице с формой обратной связи нужно под тем же логином, по которому вы хотите получить консультацию в Директе. Мы остаемся на связи! Пожалуйста, оцените мой ответ-С уважением, НаталияОтдел клиентского сервисател.: 8 800 234-24-80 (круглосуточно, звонок из регионов России бесплатный)тел.: +7 495 739-37-77  Настоящее сообщение и все приложения к нему предназначены только для их получателей и содержат конфиденциальную информацию и коммерческую тайну ООО «ЯНДЕКС». Их разглашение, передача третьим лицам либо иное распространение или копирование является нарушением прав ООО «ЯНДЕКС». Если вы получили настоящее сообщение по ошибке, пожалуйста, уведомите об этом отправителя и/или ООО «ЯНДЕКС» по электронной почте ответным письмом и удалите настоящее сообщение и/или всю переписку без возможности восстановления.    14.09.2022, 13:15, "Vesta Cute" ***@***.***>:В Xcode 14 появилась новая проблема при выгрузке приложения в AppStore (приложение загружается, но с ошибками). В предыдущей версии Xcode этой ошибки не было—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by diniska** [comment]
У меня та-же петрушка. Выдает предупреждение при заливке в AppStore. Могу подтвердить, что это в итоге не мешает выкладке приложения. Моё приложение было опубликовано в AppStore сегодня несмотря на это предупреждение.

**Comment by Knochenmann** [comment]
Аналогичный варнинг в Xcode 14. В 13.4.1 все хорошо.

**Comment by GLinnik21** [comment]
Рассмотрели в #104
