### ISSUE TITLE
Crash: ru.yandex.mobile.YandexMobileMetrica.YMMServer.Queue EXC_GUARD 0x08fd4dbfade2dead

### ISSUE THREAD

**Issue by VladimirLyseev** [yandexmobile/metrica-sdk-ios#77]
Stack trace:
0  0x1cf2c3f44 close + 8
1  0x1025aa4d8 -[YMMConnectionAcceptor closeSocket] + 1236184
2  0x1025aa594 -[YMMConnectionAcceptor stop] + 1236372
3  0x1025aa870 __async_wait_block_invoke + 1237104
4  0x102599050 __28-[YMMAsyncExecutor execute:]_block_invoke + 1165392
5  0x1cf1656c8 _dispatch_call_block_and_release + 24
6  0x1cf166484 _dispatch_client_callout + 16
7  0x1cf10dbe0 _dispatch_lane_serial_drain$VARIANT$mp + 592
8  0x1cf10e728 _dispatch_lane_invoke$VARIANT$mp + 432
9  0x1cf116ec8 _dispatch_workloop_worker_thread + 600
10 0x1cf3480dc _pthread_wqthread + 312
11 0x1cf34acec start_wqthread + 4

Crashed after applicationDidEnterBackground:

**Comment by davomere** [comment]
Hello, did you solve the issue?

**Comment by dzinad** [comment]
Hello. Please specify AppMetrica SDK version you're using.

**Comment by AppMetricaOvermindGenius180iq** [comment]
Can you please test it on our newest version of AppMetrica SDK (3.14.1). If it persists there, you can write us new issue.

**Comment by Semty** [comment]
The issue is still here, but only on spm (I've used appmetrica via cocoapods and everything was fine). Stack trace:

`Crashed: ru.yandex.mobile.YandexMobileMetrica.YMMCancelableDelayedExecutor.Queue
0  libobjc.A.dylib                0x3490 objc_retain + 16
1  YandexMobileMetrica            0x70938 _hidden#6546_ + 21548
2  YandexMobileMetrica            0xbfce4 _hidden#10344_ + 266920
3  YandexMobileMetrica            0xbff88 _hidden#10348_ + 267596
4  YandexMobileMetrica            0xbff28 _hidden#10347_ + 267500
5  YandexMobileMetrica            0x9d64c _hidden#8694_ + 125968
6  libdispatch.dylib              0x1c04 _dispatch_call_block_and_release + 32
7  libdispatch.dylib              0x3950 _dispatch_client_callout + 20
8  libdispatch.dylib              0xb0ac _dispatch_lane_serial_drain + 664
9  libdispatch.dylib              0xbc10 _dispatch_lane_invoke + 392
10 libdispatch.dylib              0x16318 _dispatch_workloop_worker_thread + 656
11 libsystem_pthread.dylib        0x11b0 _pthread_wqthread + 288
12 libsystem_pthread.dylib        0xf50 start_wqthread + 8`

iPhone 11, iOS 15.0.2

**Comment by GLinnik21** [comment]
> edit: it's better to create a new issue for that, I suppose
Yeah, it seems that crash is different
