### ISSUE TITLE
Version 3.14.0 writes some user build settings which causes errors

### ISSUE THREAD

**Issue by OneSman7** [yandexmobile/metrica-sdk-ios#91]
In this version you used user_target_xcconfig which is not recommended (https://guides.cocoapods.org/syntax/podspec.html#user_target_xcconfig).
I am using Apple Silicon MacBook and have to override Excluded Architectures for many projects sine only major library providers started adopting XCFramworks for static libraries. But your setting did override mine and I had to spend time researching from where this setting have come.

**Comment by GLinnik21** [comment]
Hello!
Indeed in 3.14.0, we had to use `user_target_xcconfig` due to [this issue](https://github.com/CocoaPods/CocoaPods/issues/10065). As you know, starting with Xcode 12 and MacBooks M1, Apple has introduced some confusions with iOS Simulator architecture. This configuration is intended to fix linking errors on Intel processors as iOS Simulator needs an arm64 slice on x86_64 by default in Xcode 12 to run (for some reason). Folks say that this is Xcode's bug. So this a common solution to fix it.
Sorry for the inconvenience. I'm sure that we should include a notice about this in 3.14.0 documentation.

**Comment by GLinnik21** [comment]
Hello!
In the latest release (3.14.1) we removed this attribute from Podspec

**Comment by OneSman7** [comment]
Great news! 👍
