### ISSUE TITLE
Crashed: ru.yandex.mobile.YandexMobileMetrica.YMMCancelableDelayedExecutor.Queue

### ISSUE THREAD

**Issue by GLinnik21** [yandexmobile/metrica-sdk-ios#99]
The issue is still here, but only on spm (I've used appmetrica via cocoapods and everything was fine). Stack trace:

```
Crashed: ru.yandex.mobile.YandexMobileMetrica.YMMCancelableDelayedExecutor.Queue
0  libobjc.A.dylib                0x3490 objc_retain + 16
1  YandexMobileMetrica            0x70938 _hidden#6546_ + 21548
2  YandexMobileMetrica            0xbfce4 _hidden#10344_ + 266920
3  YandexMobileMetrica            0xbff88 _hidden#10348_ + 267596
4  YandexMobileMetrica            0xbff28 _hidden#10347_ + 267500
5  YandexMobileMetrica            0x9d64c _hidden#8694_ + 125968
6  libdispatch.dylib              0x1c04 _dispatch_call_block_and_release + 32
7  libdispatch.dylib              0x3950 _dispatch_client_callout + 20
8  libdispatch.dylib              0xb0ac _dispatch_lane_serial_drain + 664
9  libdispatch.dylib              0xbc10 _dispatch_lane_invoke + 392
10 libdispatch.dylib              0x16318 _dispatch_workloop_worker_thread + 656
11 libsystem_pthread.dylib        0x11b0 _pthread_wqthread + 288
12 libsystem_pthread.dylib        0xf50 start_wqthread + 8
```

iPhone 11, iOS 15.0.2

edit: it's better to create a new issue for that, I suppose

_Originally posted by @Semty in https://github.com/yandexmobile/metrica-sdk-ios/issues/77#issuecomment-955697735_

**Comment by AppMetricaOvermindGenius180iq** [comment]
Добрый день!Ваше письмо получено и зарегистрировано под уникальным номером № 14569889. Ответ обязательно будет предоставлен, пожалуйста, ожидайте.Просим Вас не отправлять повторное письмо по данному вопросу - оно будет считаться новой заявкой и может быть обработано позднее.Помощь сервиса: https://yandex.ru/support/direct/?from=email--С уважением,Отдел клиентского сервисател.: 8 800 234-24-80 (звонок из регионов России бесплатный)тел.: +7 495 739-37-77&nbsp01.11.2021, 14:43, "Gleb Linnik" ***@***.***>:
The issue is still here, but only on spm (I've used appmetrica via cocoapods and everything was fine). Stack trace:
Crashed: ru.yandex.mobile.YandexMobileMetrica.YMMCancelableDelayedExecutor.Queue
0  libobjc.A.dylib                0x3490 objc_retain + 16
1  YandexMobileMetrica            0x70938 _hidden#6546_ + 21548
2  YandexMobileMetrica            0xbfce4 _hidden#10344_ + 266920
3  YandexMobileMetrica            0xbff88 _hidden#10348_ + 267596
4  YandexMobileMetrica            0xbff28 _hidden#10347_ + 267500
5  YandexMobileMetrica            0x9d64c _hidden#8694_ + 125968
6  libdispatch.dylib              0x1c04 _dispatch_call_block_and_release + 32
7  libdispatch.dylib              0x3950 _dispatch_client_callout + 20
8  libdispatch.dylib              0xb0ac _dispatch_lane_serial_drain + 664
9  libdispatch.dylib              0xbc10 _dispatch_lane_invoke + 392
10 libdispatch.dylib              0x16318 _dispatch_workloop_worker_thread + 656
11 libsystem_pthread.dylib        0x11b0 _pthread_wqthread + 288
12 libsystem_pthread.dylib        0xf50 start_wqthread + 8

iPhone 11, iOS 15.0.2
edit: it's better to create a new issue for that, I suppose
Originally posted by @Semty in #77 (comment)

**Comment by GLinnik21** [comment]
Duplicate of #98
